import { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Premium Cotton T-Shirt',
    description: 'High-quality 100% cotton t-shirt for everyday wear.',
    category: 'clothing',
    subcategory: 'T-Shirts',
    gender: 'men',
    color: 'Black',
    price: 25,
    priceINR: 1999,
    priceUSD: 25,
    images: ['https://picsum.photos/seed/tshirt1/600/800'],
    stock: 100,
    sellerId: 'seller1',
    rating: 4.5,
    reviewsCount: 120,
    isTrending: true,
    season: 'summer',
    variants: {
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Black', 'White', 'Navy']
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p1-white',
    name: 'Premium Cotton T-Shirt (White)',
    description: 'High-quality 100% cotton t-shirt for everyday wear.',
    category: 'clothing',
    subcategory: 'T-Shirts',
    gender: 'men',
    color: 'White',
    price: 25,
    priceINR: 1999,
    priceUSD: 25,
    images: ['https://picsum.photos/seed/tshirt-white/600/800'],
    stock: 100,
    sellerId: 'seller1',
    rating: 4.5,
    reviewsCount: 120,
    season: 'summer',
    variants: {
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Black', 'White', 'Navy']
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p2',
    name: 'Silk Saree',
    description: 'Elegant silk saree with intricate embroidery.',
    category: 'clothing',
    subcategory: 'Ethnic',
    gender: 'women',
    color: 'Red',
    price: 150,
    priceINR: 11999,
    priceUSD: 150,
    images: ['https://picsum.photos/seed/saree1/600/800'],
    stock: 20,
    sellerId: 'seller1',
    rating: 4.8,
    reviewsCount: 45,
    isTrending: true,
    season: 'all',
    variants: {
      colors: ['Red', 'Gold', 'Blue']
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p3',
    name: 'Denim Fabric',
    description: 'Durable denim fabric for jeans and jackets.',
    category: 'fabric',
    subcategory: 'Cotton',
    price: 12,
    priceINR: 999,
    priceUSD: 12,
    images: ['https://picsum.photos/seed/fabric1/600/800'],
    stock: 5000,
    sellerId: 'seller2',
    rating: 4.2,
    reviewsCount: 30,
    season: 'all',
    fabricInfo: {
      gsm: 350,
      material: 'Cotton Denim',
      colors: ['Indigo', 'Light Blue', 'Black'],
      minOrder: 50
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p4',
    name: 'Linen Fabric',
    description: 'Breathable linen fabric perfect for summer clothing.',
    category: 'fabric',
    subcategory: 'Linen',
    price: 18,
    priceINR: 1499,
    priceUSD: 18,
    images: ['https://picsum.photos/seed/fabric2/600/800'],
    stock: 3000,
    sellerId: 'seller2',
    rating: 4.7,
    reviewsCount: 15,
    season: 'summer',
    fabricInfo: {
      gsm: 200,
      material: 'Pure Linen',
      colors: ['White', 'Beige', 'Sage'],
      minOrder: 50
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p5',
    name: 'Slim Fit Chinos',
    description: 'Modern slim fit chinos for a sharp look.',
    category: 'clothing',
    subcategory: 'Pants',
    gender: 'men',
    color: 'Khaki',
    price: 45,
    priceINR: 3599,
    priceUSD: 45,
    images: ['https://picsum.photos/seed/chinos1/600/800'],
    stock: 50,
    sellerId: 'seller1',
    rating: 4.4,
    reviewsCount: 88,
    season: 'all',
    variants: {
      sizes: ['30', '32', '34', '36'],
      colors: ['Khaki', 'Olive', 'Navy']
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p6',
    name: 'Floral Summer Dress',
    description: 'Lightweight floral dress for warm days.',
    category: 'clothing',
    subcategory: 'Dresses',
    gender: 'women',
    color: 'Yellow',
    price: 65,
    priceINR: 5199,
    priceUSD: 65,
    images: ['https://picsum.photos/seed/dress1/600/800'],
    stock: 35,
    sellerId: 'seller1',
    rating: 4.6,
    reviewsCount: 56,
    isTrending: true,
    season: 'summer',
    variants: {
      sizes: ['XS', 'S', 'M', 'L'],
      colors: ['Yellow', 'Pink']
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p13',
    name: 'Kids Cotton Hoodie',
    description: 'Soft and warm cotton hoodie for kids.',
    category: 'clothing',
    subcategory: 'Hoodies',
    gender: 'kids',
    color: 'Blue',
    price: 35,
    priceINR: 2799,
    priceUSD: 35,
    images: ['https://picsum.photos/seed/kidshoodie1/600/800'],
    stock: 60,
    sellerId: 'seller1',
    rating: 4.7,
    reviewsCount: 42,
    season: 'winter',
    variants: {
      sizes: ['4Y', '6Y', '8Y', '10Y'],
      colors: ['Blue', 'Red', 'Grey']
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p14',
    name: 'Kids Denim Overalls',
    description: 'Classic denim overalls for active kids.',
    category: 'clothing',
    subcategory: 'Overalls',
    gender: 'kids',
    color: 'Indigo',
    price: 40,
    priceINR: 3199,
    priceUSD: 40,
    images: ['https://picsum.photos/seed/kidsdenim1/600/800'],
    stock: 45,
    sellerId: 'seller1',
    rating: 4.5,
    reviewsCount: 28,
    season: 'all',
    variants: {
      sizes: ['2Y', '4Y', '6Y'],
      colors: ['Indigo']
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p15',
    name: 'Winter Wool Coat',
    description: 'Elegant wool coat for cold winter days.',
    category: 'clothing',
    subcategory: 'Coats',
    gender: 'women',
    color: 'Camel',
    price: 180,
    priceINR: 14399,
    priceUSD: 180,
    images: ['https://picsum.photos/seed/woolcoat1/600/800'],
    stock: 20,
    sellerId: 'seller1',
    rating: 4.9,
    reviewsCount: 15,
    isTrending: true,
    season: 'winter',
    variants: {
      sizes: ['S', 'M', 'L'],
      colors: ['Camel', 'Black', 'Grey']
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'p16',
    name: 'Blue Graphic T-Shirt',
    description: 'Cool graphic t-shirt in vibrant blue.',
    category: 'clothing',
    subcategory: 'T-Shirts',
    gender: 'men',
    color: 'Blue',
    price: 28,
    priceINR: 2249,
    priceUSD: 28,
    images: ['https://picsum.photos/seed/bluetshirt/600/800'],
    stock: 80,
    sellerId: 'seller1',
    rating: 4.3,
    reviewsCount: 64,
    season: 'summer',
    variants: {
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Blue']
    },
    createdAt: new Date().toISOString()
  }
];
